- name: Install Nginx server
  ansible.builtin.package:
    name: nginx
    state: present
- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
- name: Remove contents of the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
    force: yes
- name: Recreate the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: Downloading frontend code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip
- name: Extracting frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: Copy expense Nginx configuration
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf 
- name: Restart the Nginx server
  ansible.builtin.service:
    name: nginx
    state: restarted






